version: "2.4"
services:
  sb-html-to-pdf-oraclexe:
    image: wnameless/oracle-xe-11g-r2
    container_name: oraclexe
    volumes:
      - ./src/main/resources/docker/oraclexe:/docker-entrypoint-initdb.d
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - 1521:1521
networks:
  sb-html-to-pdf-net:
    name: sb-html-to-pdf-net