version: "2.4"
services:
  springboot-avaliacao:
    image: wnameless/oracle-xe-11g-r2
    container_name: springboot-avaliacao
    volumes:
      - ./src/main/resources/docker/oraclexe:/docker-entrypoint-initdb.d
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - 1521:1521
networks:
  springboot-fintech-api-net:
    name: avaliacao-net